<table width="100%"  border="0" cellspacing="0" cellpadding="0" bgcolor="#cc0000">
<tr>
<td class="readers_frame_bg"><img src="../../images/logo.jpg" alt="The National Archives" width="131" height="72"></td>
<td class="readers_frame_bg">
<div align="right"><a href="/default.asp" target="_top"><img src="../../images/title-sm-accessinfo.gif" alt="access to information resources" width="259" height="31" border="0"></a></div>
<div>
	 <table width="100%"  border="0" cellspacing="0" cellpadding="0">
	<tr><td colspan="8" class="readers_frame_sep"><img src="../../images/readers_frame_strip.jpg" alt="Images of the National Archives" width="866" height="17">
	</td></tr>
        <tr class="readers_frame_sep">
          <td class="readers_frame_sep_right">&nbsp;<span class="readers_frame_text"><a href="/default.asp" title="Return to main page" target="_top">Main</a></span></td>
          <td class="readers_frame_sep_right"><span class="readers_frame_text"><a href="/orderdocuments/default.asp" title="Catalogue &amp; Document Ordering">Catalogue &amp; Ordering</a></span></td>
          <td class="readers_frame_sep_right"><span class="readers_frame_text"><a href="/frame.asp?wrap=1" title="Quick guide to the National Archives facilities">Guide</a></span></td>
          <td class="readers_frame_sep_right"><span class="readers_frame_text"><a href="http://www.nationalarchives.gov.uk/" title="The National Archives website">Website</a></span></td>
          <td class="readers_frame_sep_right"><span class="readers_frame_text"><a href="/frame.asp?wrap=3" title="Other useful websites">&nbsp;Other Sites&nbsp;</a></span></td>
          <td class="readers_frame_sep_right"><span class="readers_frame_text"><a href="/frame.asp?wrap=4" title="Other Catalogues &amp; registers">Other Catalogues</a></span></td>
          <td class="readers_frame_sep_right"><span class="readers_frame_text"><a href="/frame.asp?wrap=6" title="Online &amp; Electronic records">Online Records</a></span></td>
          <td class="readers_frame_sep"><span class="readers_frame_text"><a href="/frame.asp?wrap=7" title="The Resource Centre &amp; Library Catalogue">Library</a></span></td>
        </tr>
      </table>
	  </div>
	  </td></tr></table>